### ISSUE TITLE
The current working directory is prepended to the ns-db-file, even if the user has already provided a full path

### ISSUE THREAD

**Issue by JuergenKosel** [Azure/iot-gateway-opc-ua-proxy#16]
Hello,

with the command line option `-d <file-name>` or `--ns-db-file <file-name>` could provide the user the file to store local name service database.
If the user provides an absolute path as argument for this option (e.g. because the proxyd should be started from some script), then the current working directory is prep-ended to the absolute path.
So that proxyd fails to open the given file.
I recommend to either document this behavior. Or to modify function pal_create_full_path() to return
file_name, if it is already an absolute path.

Greetings
  Juergen

**Comment by marcschier** [comment]
This will be fixed soon.

Outlook for Android<https://aka.ms/ghei36> herunterladen


________________________________

**Comment by JuergenKosel** [comment]
Fixed in 0e4d9afe
